name: CI — Build, Scan, Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/sample-app

jobs:
  ################################################################
  # Stage 1 — Security scan on source code
  ################################################################
  scan-code:
    name: Scan Source Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy on filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: app/
          severity: HIGH,CRITICAL
          exit-code: 0   # warn only — don't block on source scan

  ################################################################
  # Stage 2 — Build and scan container image
  ################################################################
  build:
    name: Build & Scan Image
    runs-on: ubuntu-latest
    needs: scan-code
    permissions:
      contents: read
      packages: write
      security-events: write
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      short-sha:    ${{ steps.sha.outputs.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: app/
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ steps.sha.outputs.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            GIT_SHA=${{ github.sha }}
            VERSION=1.0.${{ github.run_number }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max

      - name: Scan container image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ steps.sha.outputs.sha }}
          severity:  HIGH,CRITICAL
          exit-code: 1   # fail build on HIGH/CRITICAL CVEs in image

  ################################################################
  # Stage 3 — Update GitOps manifests (triggers ArgoCD sync)
  ################################################################
  update-manifests:
    name: Update GitOps Manifests
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set target environment
        id: env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env=staging" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi

      - name: Install Kustomize
        run: |
          curl -sLO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.1/kustomize_v5.4.1_linux_amd64.tar.gz
          tar xzf kustomize_v5.4.1_linux_amd64.tar.gz
          sudo mv kustomize /usr/local/bin/

      - name: Update image tag in overlay
        run: |
          cd kubernetes/overlays/${{ steps.env.outputs.env }}
          kustomize edit set image \
            ghcr.io/your-org/sample-app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ needs.build.outputs.short-sha }}

      - name: Commit manifest update
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add kubernetes/overlays/${{ steps.env.outputs.env }}/kustomization.yaml
          git diff --staged --quiet || \
            git commit -m "chore: deploy sha-${{ needs.build.outputs.short-sha }} to ${{ steps.env.outputs.env }}"
          git push

  ################################################################
  # Stage 4 — Promote to prod (requires manual approval)
  ################################################################
  promote-prod:
    name: Promote to Production
    runs-on: ubuntu-latest
    needs: update-manifests
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://app.example.com
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Kustomize
        run: |
          curl -sLO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.1/kustomize_v5.4.1_linux_amd64.tar.gz
          tar xzf kustomize_v5.4.1_linux_amd64.tar.gz
          sudo mv kustomize /usr/local/bin/

      - name: Update prod image tag
        run: |
          cd kubernetes/overlays/prod
          kustomize edit set image \
            ghcr.io/your-org/sample-app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ needs.build.outputs.short-sha }}

      - name: Commit prod manifest update
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add kubernetes/overlays/prod/kustomization.yaml
          git diff --staged --quiet || \
            git commit -m "chore: promote sha-${{ needs.build.outputs.short-sha }} to prod"
          git push
