# ApplicationSet — one definition generates ArgoCD apps for all environments
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://kubernetes.default.svc
            namespace: sample-app-dev
          - env: staging
            cluster: https://kubernetes.default.svc
            namespace: sample-app-staging
          - env: prod
            cluster: https://kubernetes.default.svc
            namespace: sample-app-prod

  template:
    metadata:
      name: "sample-app-{{env}}"
      namespace: argocd
    spec:
      project: applications
      source:
        repoURL: https://github.com/your-org/gitops-eks-demo
        targetRevision: HEAD
        path: "kubernetes/overlays/{{env}}"
      destination:
        server: "{{cluster}}"
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
